### ISSUE TITLE
Abstract for Alex-Murray Leslie

### ISSUE THREAD

**Issue by ghost** [danewatkins/sar#38]
Ready to Foot:
Decolonising the feet through Demaking High Heeled shoes
for audiovisual theatrical performance and a new location of knowledge

The feet play the role of support structures or even infrastructure for the rest of the body, especially for the hands. The hands, the head and the eyes are the glorified organs of vision, manipulation, tactility and calculation and the feet are a kind of infrastructural support that philosophers never bothered to speak about that much – with notable exceptions such as Bataille, who believes in order to undo the division of labour as proposed by Charles Darwin one would have to effectively want to challenge, suspend, reverse, invert or maybe undo that division of labour, which brings up colonised questions, the feet are colonised by the body, the feet are the colonial subject, the feet are being colonised by the body, so in that sense this research aims to decolonise that hierarchy that has formatted the body as this and elevated the hand at the expense of the feet.

We can use our feet for more than just walking around and some people actually develop extraordinary dexterity with their feet, not only using them to do everyday tasks, but even activities like painting or playing an instrument. Through training, it is possible for the feet to carry out complex creative tasks, beyond their normal everyday job as 'stepping machines’ (Ingold 2003). I agree that a more grounded approach to the way we move as humans can open up new terrain in the area of embodied foot-based skills.

Martin Heidegger proposed that objects may be experienced in two different ways as ‘ready to hand’ and ‘present at hand’ (Heidegger 1962). When an object is ‘ready to hand’ it performs like a seamless extension of our bodily motions. When an object is ‘present at hand’ we perceive it as independent of our bodies, as an agent to be acted upon and with, rather than through. The computer enhanced foot prototypes discussed in this research cannot be physically separated from the foot in performance, the two are tightly, and consistently coupled to carry out theatrical tasks. i therefore suggest the possibility of a knowledge connected to the very experiences that are ‘present at foot'. The theme of 'knowledge at foot’ and objects being ‘ready to foot' relates to situations where the feet are the location of the generation of new knowledge via practice based research and the creation of artefacts (i term Anthropotechnological foot-prototypes and computer enhanced footwear).

Shoes in many cases deform feet. It is this unfree state of the feet that this research challenges through finding unexpected ways to use our feet in newly designed computer enhanced footwear. These foot devices use new technologies coupled with sensors and FM sound synthesis, and therefore afford new types of bodily extensions for creative expression.  Through the praxis, I explore and demonstrate the expressive role of the feet in lens-based performance art and their potential impact on the way we perform when enhanced with technology to produce a multi-sensory experience. This approach places the computer enhanced foot-wear in critical dialogue with contemporary technologies for shaping corporeal experience and reimagining foot-centric technologies, to inform unexpected outcomes and communicative ideas through internal bodily awareness. In relation to this research, therefore it is an essential element of the computer enhanced footwear and use of technology that it is from a social perspective taking into account the theory of ‘humanistic intelligence’ (Mann 2001) rather than an ‘artificial intelligence’. I explore the development of foot based skills in the area of audio-visual performance and the related creation of audio-visual instruments created to costume and decolonise the feet.

**Comment by danewatkins** [comment]
That is very long and who is Bataile?

On 12 Mar 2018 09:12, "anyalewin" <notifications@github.com> wrote:

The feet play the role of support structures or even infrastructure for the
rest of the body, especially for the hands. The hands, the head and the
eyes are the glorified organs of vision, manipulation, tactility and
calculation and the feet are a kind of infrastructural support that
philosophers never bothered to speak about that much – with notable
exceptions such as Bataile, who believes in order to undo the division of
labour as proposed by Charles Darwin one would have to effectively want to
challenge, suspend, reverse, invert or maybe undo that division of labour,
which brings up colonised questions, the feet are colonised by the body,
the feet are the colonial subject, the feet are being colonised by the
body, so in that sense this research aims to decolonise that hierarchy that
has formatted the body as this and elevated the hand at the expense of the
feet.

We can use our feet for more than just walking around and some people
actually develop extraordinary dexterity with their feet, not only using
them to do everyday tasks, but even activities like painting or playing an
instrument. Through training, it is possible for the feet to carry out
complex creative tasks, beyond their normal everyday job as 'stepping
machines’ (Ingold 2003). I agree that a more grounded approach to the way
we move as humans can open up new terrain in the area of embodied
foot-based skills.

Martin Heidegger proposed that objects may be experienced in two different
ways as ‘ready to hand’ and ‘present at hand’ (Heidegger 1962). When an
object is ‘ready to hand’ it performs like a seamless extension of our
bodily motions. When an object is ‘present at hand’ we perceive it as
independent of our bodies, as an agent to be acted upon and with, rather
than through. The computer enhanced foot prototypes discussed in this
research cannot be physically separated from the foot in performance, the
two are tightly, and consistently coupled to carry out theatrical tasks. i
therefore suggest the possibility of a knowledge connected to the very
experiences that are ‘present at foot'. The theme of 'knowledge at foot’
and objects being ‘ready to foot' relates to situations where the feet are
the location of the generation of new knowledge via practice based research
and the creation of artefacts (i term Anthropotechnological foot-prototypes
and computer enhanced footwear).

Shoes in many cases deform feet. It is this unfree state of the feet that
this research challenges through finding unexpected ways to use our feet in
newly designed computer enhanced footwear. These foot devices use new
technologies coupled with sensors and FM sound synthesis, and therefore
afford new types of bodily extensions for creative expression. Through the
praxis, I explore and demonstrate the expressive role of the feet in
lens-based performance art and their potential impact on the way we perform
when enhanced with technology to produce a multi-sensory experience. This
approach places the computer enhanced foot-wear in critical dialogue with
contemporary technologies for shaping corporeal experience and reimagining
foot-centric technologies, to inform unexpected outcomes and communicative
ideas through internal bodily awareness. In relation to this research,
therefore it is an essential element of the computer enhanced footwear and
use of technology that it is from a social perspective taking into account
the theory of ‘humanistic intelligence’ (Mann 2001) rather than an
‘artificial intelligence’. I explore the development of foot based skills
in the area of audio-visual performance and the related creation of
audio-visual instruments created to costume and decolonise the feet.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/danewatkins/sar/issues/38>, or mute the thread

**Comment by ghost** [comment]
It doesn’t matter if it is long for the web does it? Can you fix Bataille.

Thanks!

**Comment by ghost** [comment]
Hi Dane,

Does this need to be shorter or can we put it on the website?

Thank You,
Anya

**Comment by danewatkins** [comment]
I can put it on, just got a lot on this week and it will take some time
formatting

**Comment by ghost** [comment]
Ok If I get a shorter version Ill post it here instead
